Hubs-Foundation/Spoke

src/client/components/PropertyGroup.js, src/client/components/PropertyGroup.scss, src/client/containers/ComponentsContainer.js, src/client/containers/NodePropertyGroupContainer.js, src/client/editor/commands/RemoveComponentCommand.js
- Changes:
- Added remove button to PropertyGroup.
- Added RemoveComponentCommand.
- Pushed the remove button to the right in PropertyGroup.scss
=> Remove button for components

src/client/assets/error-icon.svg, src/client/assets/warning-icon.svg, src/client/editor/SceneLoader.js, src/client/theme.scss, src/client/ui/SnackBar.js, src/client/ui/SnackBar.scss, src/client/ui/panels/HierarchyPanelContainer.js, src/client/ui/panels/HierarchyPanelContainer.scss, src/client/vendor/react-ui-tree/index.scss
- Changes:
- added `SnackBar.js` to display different types of conflicts.
- checked missing nodes in `SceneLoader.js`.
- changed css styles for ui tree nodes.
- added warning snackbar rendering in `HeirarchyPanelContainer.js`.
=> warning displays - renamed/deleted nodes in the inherited scene file

package-lock.json, package.json, src/client/editor/components/AmbientLightComponent.js, src/client/editor/components/DirectionalLightComponent.js, src/client/editor/components/PointLightComponent.js, src/client/editor/components/StandardMaterialComponent.js, src/client/ui/inputs/NumericInput.js, src/client/ui/inputs/NumericInput.scss, src/client/ui/inputs/Vector3Input.scss, src/client/ui/inputs/componentTypeMappings.js, src/client/ui/panels/PropertiesPanelContainer.js
Implemented a `NumericInput` that fixes a lot of the flaws of `react-numeric-input`. This avoids messing with your manual typing as much as possible but still fires `onChange` if it sees a valid number while you're typing.
It allows you to edit partial numbers, negative numbers and decimals as if it were a regular old `<input />` and only attempts to validate and reformat the number when you blur the input or a new prop value comes in. 
It also avoids state changes if the incoming prop value is equivalent to, but not exactly, the current input state, so that your typing isn't interrupted by an `onChange` cycle.
In addition to the fixes, it also provides these features:
- Mouse scrubbing with pointer-lock on the middle mouse button
- Scroll wheel scrubbing
- Arrow key increment/decrement
- …
=> Enhanced numeric input with bugfixes, scrubbing, scrolling and arrowkeys

src/client/ui/inputs/ColorInput.scss
- made the color picker respect to the container.
- made the click cover not to overlap with the scrollbar of the property panel.
=> Color Picker Position

package.json, src/client/editor/Editor.js, src/client/editor/SceneLoader.js, src/client/editor/commands/AddComponentCommand.js, src/client/editor/commands/RemoveComponentCommand.js, src/client/editor/components/AmbientLightComponent.js, src/client/editor/components/BaseComponent.js, src/client/editor/components/DirectionalLightComponent.js, src/client/editor/components/PointLightComponent.js, src/client/editor/components/ShadowComponent.js, src/client/editor/components/SkyboxComponent.js, src/client/editor/components/StandardMaterialComponent.js, src/client/editor/components/TransformComponent.js, src/client/ui/EditorContainer.js, src/client/ui/dialogs/ProgressDialog.js, src/client/ui/panels/PropertiesPanelContainer.js
Ignore scene modification signals while the scene is loading
In order to do the above, I had to make `addComponent` (and subsequently `updateProperty` and `inflate`) asynchronous. This actually solves a number of issues and is just the right thing to do, since these operations are inherently async and we want to await on them, e.g. when loading scene references or material textures.
Fixes #97
=> Fix scene modification state

src/client/ui/inputs/ColorInput.js, src/client/ui/inputs/ColorInput.scss, src/client/vendor/react-mosaic-component/mosaic-window.scss
- flatten the z-index of `mosaic-window-body`.
- made the color picker on the top.
- fixes #157
=> Make colorpicker pop over

src/client/editor/Editor.js, src/client/editor/components/NavMeshComponent.js, src/client/editor/components/VisibleComponent.js
This PR:
- Renames the nav mesh node to be "Floor Plan"
- Adds a description
- Re-orders the components so the nav mesh is first
- Toggles on/off visibility when selected in heirarchy
=> Nav mesh UX tweaks

README.md, package.json
It seems like there's no reason we ever want to run the server over HTTPS nowadays, so let's not make it the default for things. Now it's easier to do `npm open foo` and have the configuration you want for opening project `foo`.
=> Fix up defaults for npm run dev/open

src/client/editor/Editor.js, src/client/editor/Viewport.js, src/client/ui/EditorContainer.js
This PR exports a camera into the GLTF for the preview on the scene page. For now, the camera is set up as taking on the transform from the screenshot's camera.
=> Export a preview camera into the GLTF

src/server/index.js
I ran into an issue where one of the Sketchfab scenes had texture files that began with a "." and so were considered hidden files, which are not available from the API before this PR. Does this seem safe to do?
=> Add hidden files

src/client/editor/Editor.js, src/client/ui/dialogs/FileDialog.js
- Prints out `An unknown error occurred.` instead of serializing the error object (`Failed to load GLTF: [object]`) when an error without a message is thrown in the gltf-model component.
- Passes the file name as a second argument when confirming the file dialog. This is passed to the gltf-model component and was previously undefined.
=> Fix gltf-model error message and undefined name

package.json
Now that we use a default project directory, it's probably best to have npm start just run against that directory.
=> Change npm run open to default npm start script

src/client/editor/Editor.js, src/client/editor/components/GLTFModelComponent.js, src/client/ui/EditorContainer.js
- Added `includeInFloorPlan` to the `gltf-model` component. This should help users exclude far away meshes that will increase the resolution of their FloorPlan, or just filter out meshes that they don't want users to navigate to.
- Always remove the first nav-mesh object and associated generated file before generating a nav mesh.
- Changed text in the file menu from `Generate nav mesh` to `Generate Floor Plan`
=> Added includeInFloorPlan prop and always remove FloorPlan on generation.

src/client/editor/Editor.js
Merges meshes in animated models by marking animated nodes as dynamic. Results in significantly less draw calls in environments using models like this: https://sketchfab.com/models/7984bd6024db4b89928ddeb625eebac0
=> Merge meshes in animated glTF models

package-lock.json, package.json
Fixes exporting ambient occlusion on a second uv set. If you want to bake AO into a texture atlas mapped to the second uv set you can now do so.
=> Fix exporting ambient occlusion on a second uv set

src/client/editor/nodes/BoxColliderNode.js, src/client/editor/nodes/GroundPlaneNode.js
The `box-collider` component in Hubs expects transform properties which I forgot to export.
=> Fix box collider component

src/client/editor/Editor.js
This PR sets the position of the directional light in the default scene to (-1, 3, 0)
Suggested by @j-conrad. Jim I tweaked the coordinates a little bit so that it's still visible but doesn't occlude the spawn point.
=> Set directional light position to a more visible default.

.env.defaults, src/server/index.js
Introduces the `HUBS_SERVER` environment variable and uses the existing `RETICULUM_SERVER` environment variable in the server in order to make Spoke work seamlessly with a locally hosted Hubs server.
=> Make it easier to test with a local copy of Hubs.

src/client/editor/objects/PhysicalDirectionalLight.js, src/client/editor/objects/PhysicalSpotLight.js
Lights in spoke don't actually need the targets to be cloned. This was resulting in odd behavior when duplicating and rotating lights.
=> Fix cloning light targets

src/client/editor/nodes/SkyboxNode.js, src/client/vendor/three.js
- Environment maps now respect material roughness.
- The cube camera now faces the correct direction for environment maps.
=> Prefilter environment map and rotate cube camera

src/client/editor/Editor.js, src/client/editor/Viewport.js, src/client/editor/nodes/EditorNodeMixin.js, src/client/editor/nodes/SkyboxNode.js
The environment map from the skybox has introduced a few new things when dealing with lighting. 
- The environment map needs to be updated when using the screenshot renderer.
- This PR renames `onAfterFirstRender` to `onRendererChanged` to better reflect when that lifecycle method is called.
- `onRendererChanged` is always called when a scene is being used with a new renderer. This happens when loading any scene (including the new scene) and when using another renderer when taking a screenshot.
- I'm not satisfied with how we are accessing the renderer in the skybox node. Hopefully, we can come up with a better way in the near future.
- In environments with a skybox, the ambient light can make the scene seem ungrounded. I've removed it from the default scene to make it simpler for people …
=> Fix scene lighting resulting from skybox environment map.

src/client/editor/Editor.js, src/client/editor/nodes/AmbientLightNode.js, src/client/editor/nodes/BoxColliderNode.js, src/client/editor/nodes/DirectionalLightNode.js, src/client/editor/nodes/EditorNodeMixin.js, src/client/editor/nodes/FloorPlanNode.js, src/client/editor/nodes/GroundPlaneNode.js, src/client/editor/nodes/GroupNode.js, src/client/editor/nodes/HemisphereLightNode.js, src/client/editor/nodes/ImageNode.js, src/client/editor/nodes/ModelNode.js, src/client/editor/nodes/PointLightNode.js, src/client/editor/nodes/SceneNode.js, src/client/editor/nodes/SkyboxNode.js, src/client/editor/nodes/SpawnPointNode.js, src/client/editor/nodes/SpawnerNode.js, src/client/editor/nodes/SpotLightNode.js, src/client/editor/nodes/VideoNode.js, src/client/editor/objects/FloorPlan.js, src/client/ui/App.js, src/client/ui/properties/BoxColliderNodeEditor.js, src/client/ui/properties/FloorPlanNodeEditor.js, src/client/ui/properties/FloorPlanNodeEditor.scss, src/client/ui/properties/GroundPlaneNodeEditor.js, src/client/ui/properties/ModelNodeEditor.js, src/client/ui/properties/NodeEditor.js, src/client/ui/properties/PropertiesPanelContainer.scss, src/client/ui/properties/TransformPropertyGroup.js, src/client/ui/viewport/AddNodeActionButtons.js, test/integration/tests/Editor.test.js
- Added the visible checkbox to every node (except the scene)
- Added the walkable checkbox to model, box collider, and ground plane nodes.
- Added the collidable checkbox to model nodes.
- A floor plan node is included in the default new scene.
- Floor plan nodes can be configured and regenerated in the properties pane.
- Old scenes will have their nodes migrated to include walkable, collidable, visible, and floor-plan components accordingly.
- The floorplan's walkable area has been reduced so that it can be included in the nav mesh generation.
- `serialize()` and `prepareForExport()` were refactored to dry up adding the `visible` component when necessary.
Fixes #307 
Fixes #274
=> Navmesh Revamp

src/editor/Editor.js, src/editor/Viewport.js, src/editor/controls/FlyControls.js, src/editor/controls/InputManager.js, src/editor/controls/input-mappings.js, src/editor/nodes/EditorNodeMixin.js, src/editor/nodes/ImageNode.js, src/editor/nodes/ModelNode.js, src/editor/nodes/VideoNode.js, src/editor/objects/Image.js, src/editor/objects/Model.js, src/editor/objects/Video.js
- Adds `editor.enterPlayMode()` and `editor.leavePlayMode()` which can be toggled in the dev tools.
- Play mode currently plays videos and animations. It also uses the new FlyControls camera controller so you can fly around your scene.
- You can still edit properties in the properties panel while in play mode although this probably still has some bugs in edge cases.
- Play mode is still experimental so save your work often if you are going to use it!
- Fixes a regression in deserializing animations
- Introduces a simple InputManager with input mappings and transforms
- Fixes image/video/models showing during loading cube animation
- Fixes #441 
- Fixes #406
=> Experimental play mode

src/editor/heightfield/HeightfieldClient.js, src/editor/heightfield/heightfield.worker.js, src/editor/nodes/FloorPlanNode.js, src/editor/objects/FloorPlan.js, src/editor/recast/RecastClient.js, src/editor/recast/recast.worker.js, src/editor/utils/cloneObject3D.js, src/editor/utils/mergeMeshGeometries.js
Added a couple fixes to @InfiniteLee's PR #624 
- Separates heightfield code into its own worker.
- Heightfields take into account spawner positions to try to determine what surfaces to exclude (e.g. ceilings).
- The navmesh is no longer used to generate the heightfield, instead the collideable geometry is used directly.
- Heightfields are generated with `raycast` instead of `raycastFirst` because `raycastFirst` only returns the first face found in the BVH, not necessarily the first intersected face. This is slower but gives very accurate results.
- The raycaster y position is set to `[large number]` (currently 1000) and uses the point.y value instead of the distance value to determine hit locations. 
- The offset value returned is updated to work with Bullet's heightmap shape. 
- Adds …
=> Improves how heightfields are generated and fixes various issues.

src/editor/caches/GLTFCache.js
Partially addresses #623
More info in https://github.com/robertlong/GLTFExporterTextureSizes
=> Use correct format for the base color map

src/editor/heightfield/heightfield.worker.js
use the "correct" raycast method, as set by `THREE.Mesh.prototype.raycast = acceleratedRaycast;`
This version ensures the raycaster and the mesh are using the same coordinate space.
=> Use acceleratedRaycast correctly

src/editor/controls/SpokeControls.js
Fixes a long standing bug:
```
TypeErrorsrc/editor/controls/SpokeControls in raycastNode
errorCannot read property 'visible' of null
```
=> Fix raycasting before project loaded

src/ui/layout/Portal.js
Fixes a long standing bug:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
=> Add guard around removeChild in portal unmount

src/ui/properties/NameInputGroup.js
Fixes a bug where clicking out of the name input, onto another node in the hierarchy panel, renamed that node.
=> Fix name input blur bug

.circleci/config.yml, src/editor/Editor.js, src/editor/controls/SpokeControls.js, src/editor/objects/Model.js, src/editor/renderer/Renderer.js, src/ui/inputs/SelectInput.js, src/ui/layout/Panel.js, src/ui/viewport/ViewportPanelContainer.js
You can now disable rendering shadows and render in wireframe and normals mode. Disabling helps improve performance while editing complex scenes. You can also now toggle the grid visibility.
=> Alternate Render Modes / Grid Toggle

package.json, src/editor/Editor.js, src/editor/controls/SpokeControls.js, src/editor/nodes/KitPieceNode.js, src/editor/nodes/ModelNode.js, src/editor/renderer/OutlinePass.js, src/editor/renderer/Renderer.js, src/editor/renderer/SpokeBatchRawUniformGroup.js, src/ui/EditorContainer.js, src/ui/Error.js, src/ui/projects/ProjectPage.js, yarn.lock
Spoke now achieves similar performance to Hubs when working with complex scenes. You can now work with hundreds of nodes in your scene without your editor slowing to a crawl.
Spoke now defaults to Unlit mode which uses batching under the hood. If you want to preview the scene as it would look in Hubs, you can switch the render mode to "Shadows" in the dropdown at top right corner of the viewport.
Also, Spoke now requires WebGL2 support. This hopefully shouldn't be a problem as most desktop browsers now support WebGL2.
=> Unlit Batching Support

src/ui/projects/templates.js
Adds the tutorial project as an option named 'Open Terrain' to the projects page as a template.
=> Add tutorial to templates as "Open Terrain"

src/editor/Editor.js, src/ui/EditorContainer.js, src/ui/router/BrowserPrompt.js
This fixes some UX issues with scene modification state, one of which is arguably a P0 issue. Most of this behavior has regressed since we no longer were setting the `sceneModified` flag to true nor firing the `sceneModified` event. 
- The `onSceneModified` event now properly fires, which wasn't working before.
- We now properly save the project on publish if it is modified. Prior to this PR, if you edited a scene, published it, and reloaded, your changes would have been lost unless you hit Save.
- The modification state is now reflected in the title of the page
- We no longer nag you about leaving the page if you have not modified the scene
Also, I wasn't sure if there was some reason this behavior was specifically altered to be more conservative (wrt warning the user) -- this PR assumed …
=> Properly handle modification state

src/editor/Editor.js, src/editor/commands/LoadMaterialSlotMultipleCommand.js, src/editor/commands/SetPropertyMultipleCommand.js, src/editor/nodes/EditorNodeMixin.js, src/editor/nodes/KitPieceNode.js, src/ui/assets/sources/ElementsSource.js, src/ui/properties/AmbientLightNodeEditor.js, src/ui/properties/BoxColliderNodeEditor.js, src/ui/properties/DirectionalLightNodeEditor.js, src/ui/properties/FloorPlanNodeEditor.js, src/ui/properties/GroundPlaneNodeEditor.js, src/ui/properties/HemisphereLightNodeEditor.js, src/ui/properties/ImageNodeEditor.js, src/ui/properties/KitPieceNodeEditor.js, src/ui/properties/LightShadowProperties.js, src/ui/properties/LinkNodeEditor.js, src/ui/properties/ModelNodeEditor.js, src/ui/properties/NameInputGroup.js, src/ui/properties/NodeEditor.js, src/ui/properties/ParticleEmitterNodeEditor.js, src/ui/properties/PointLightNodeEditor.js, src/ui/properties/PropertiesPanelContainer.js, src/ui/properties/SkyboxNodeEditor.js, src/ui/properties/SpawnerNodeEditor.js, src/ui/properties/SpotLightNodeEditor.js, src/ui/properties/TransformPropertyGroup.js, src/ui/properties/TriggerVolumeNodeEditor.js, src/ui/properties/VideoNodeEditor.js
You can now edit the properties of multiple selected objects at the same time! If the objects are of the same type you'll see all of the object properties in the properties panel. Changing the property will change all of the selected objects. Some properties such as animation may be disabled if all objects do not have the same options for that property. If you select objects with different types you will still see the transform, visibility, and name fields. Changes to the translation properties will be applied relative to the objects current position. Rotation and scale values will set absolutely.
=> Multiple Object Editing

src/api/Api.js
Currently the creator attribution is pulled from a deprecated key on the scene. This PR pulls from the correct creator attribution when it exists.
Creator attribution should then:
- Use the existing value when republishing
- Use the value saved in local storage when publishing a new scene
- For legacy scenes without a scene associated with their project (projects previously stored the scene id in the project file itself, not in the db), the value stored in the project file's metadata will be used
- Otherwise be an empty string, including when remixing an existing scene because the creator attribution is held in the parent scene
=> Fix attribution republishing

src/ui/EditorContainer.js
The Spoke file should contain the remixer's attribution, not the creator's. The creator's attribution is stored in the db.
=> Delete creator attribution when remixing

src/api/Api.js
See https://github.com/mozilla/reticulum/pull/319, uploads are now performed by connecting directly to the reticulum server.
=> Perform upload to server directly

src/ui/assets/AssetDropZone.js
Before uploading, the user might not have been signed in and the My Assets source might not be enabled. This PR only sets the source after a successful upload when the user is guaranteed to be authenticated.
=> Only set asset source after uploading

package.json, src/ui/assets/AssetManifestSource.js, src/ui/assets/KitSource.js, src/ui/assets/sources/ArchitectureKitSource.js, src/ui/assets/sources/ElementsSource.js, src/ui/assets/sources/index.js, src/ui/assets/useAssetSearch.js, src/ui/inputs/AudioInput.js, src/ui/inputs/ImageInput.js, src/ui/inputs/ModelInput.js, src/ui/inputs/StringInput.js, src/ui/inputs/VideoInput.js, yarn.lock
Reduce media API calls in the assets panel and when changing media src properties.
The asset panel now debounces calls for 500ms for any requests hitting the media API (and the architecture kit because images take a while to load and it makes for a better UX).
Changes to the media src property now only applies on blur. Pressing the escape or enter key blurs the input and triggers the change.
=> Reduce media api calls

src/index.js
Sentry was calling `toJSON` on any argument passed to console.log/warn/error. This in turn was calling `THREE.Texture.toJSON` in the `BatchManager` which then converted the image to a data URL. We don't want the extra arguments in our sentry logs anyways. Hopefully this fixes the scene load performance on production.
=> Don't serialize and send console arguments to Sentry.

src/editor/nodes/ModelNode.js
Current code assumes if `extras` exists on `asset` that it must have an `author`. The Hubs Blender Exporter now includes `"HUBS_blenderExporterVersion" : "0.0.3"` in asset extras, but not an author, which prevents Spoke from loading any GLTFs created by that exporter.
=> Don't require author in asset extras

src/editor/nodes/ImageNode.js, src/editor/objects/Image.js, src/ui/layout/Tooltip.js, src/ui/properties/ImageNodeEditor.js
Adds the option to set transparency mode for images. By default new image elements will be set to "none". Any existing images will default to "alpha" to preserve the original behavior. Hubs is similarly configured to load media components without this setting defaulting to the old behavior (alpha).
Hubs PR https://github.com/mozilla/hubs/pull/2605
=> Add "alpha mode" setting for images

src/api/Api.js, src/config.js, src/editor/Editor.js, src/editor/nodes/ScenePreviewCameraNode.js, src/editor/renderer/Renderer.js, src/ui/EditorContainer.js, src/ui/properties/ScenePreviewCameraNodeEditor.js
Spoke has always used the camera position when you save or publish to generate the thumbnail for a project and scene. This has been a major pain point for many users and now there's a solution. The Scene Preview Camera Node can be placed once in your scene and it will always be used to position the camera used for generating scene and project thumbnails. It also represents the starting position of the scene preview camera in Hubs. If you don't add a scene preview camera, one will be added for you the next time you publish your scene.
Fixes #284 
Closes https://github.com/mozilla/hubs/issues/2666
=> Add Scene Preview Camera Node

src/editor/MeshCombinationGroup.js, src/editor/gltf/GLTFLoader.js
Fixes #999 This PR updates the ThreeJS material maps tranforms based on the available maps transforms when a GLTF model is loaded.
=> Update maps transforms if available in GLTF

src/ui/properties/LinkNodeEditor.js
I had no idea the Link element could link to a website because the description only mentioned it was for linking to hub rooms.
=> Better describe what the Link element does.

src/editor/MeshCombinationGroup.js, src/editor/nodes/EditorNodeMixin.js, src/editor/nodes/KitPieceNode.js, src/editor/nodes/ModelNode.js, src/editor/nodes/SceneNode.js, src/editor/objects/Model.js, src/ui/inputs/SelectInput.js, src/ui/properties/KitPieceNodeEditor.js, src/ui/properties/ModelNodeEditor.js
Spoke now supports multiple animations per model. After importing a model from Sketchfab or your favorite 3D tool, you can now select multiple animations to loop in the Spoke property panel.
There is also a new checkbox to ignore mesh combination for a specific model. This can be useful when you want to add dynamic behavior to an object in your custom Hubs Cloud client.
Fixes #924 Support multiple animations on a single model
Depends on https://github.com/mozilla/hubs/pull/3061
=> Support multiple animations on a single model

src/ui/properties/WayPointNodeEditor.js
Fix https://github.com/mozilla/Spoke/issues/996
There was a typo in the node editor for waypoints that prevented users from disabling teleport.
In Spoke we had a mix of `willDisableTeleporting` and `willDisableTeleport` :
```js
./test/integration/snapshots/Editor.test.js.md:2114:                willDisableTeleporting: false,
./test/fixtures/V4TestScene.spoke:1:[Omitted long matching line]
./src/editor/nodes/WayPointNode.js:31:    this.willDisableTeleporting = false;
./src/editor/nodes/WayPointNode.js:53:    this.willDisableTeleporting = source.willDisableTeleporting;
./src/editor/nodes/WayPointNode.js:76:        willDisableTeleporting: this.willDisableTeleporting,
./src/editor/nodes/WayPointNode.js:92:    node.willDisableTeleporting = waypoint.props.willDisableTeleporting; …
```
=> Fix bug that makes it impossible to disable teleporting

src/editor/nodes/KitPieceNode.js, src/editor/nodes/ModelNode.js, src/editor/objects/Model.js, src/ui/properties/KitPieceNodeEditor.js, src/ui/properties/ModelNodeEditor.js
This PR addresses some of the issues spotted by @johnshaughnessy here: https://github.com/mozilla/Spoke/pull/1029#pullrequestreview-502405581
- Update animation variables to be less confusing
- Correctly handle the animations deserialization. We we currently just populating `activeClipIndices` with the animation indices but that struct actually holds `SelectInput` items so we need to recreate those items based on the persisted animation indices.
=> Fix animation import issues

src/api/Api.js, src/api/PublishDialog.js, src/editor/nodes/EditorNodeMixin.js, src/editor/nodes/ImageNode.js, src/editor/nodes/ModelNode.js, src/editor/nodes/SceneNode.js, src/editor/nodes/SpawnerNode.js, src/editor/nodes/VideoNode.js, src/editor/objects/AudioSource.js, src/editor/objects/Model.js, src/editor/objects/Video.js, src/ui/properties/AttributionNodeEditor.js, src/ui/properties/ImageNodeEditor.js, src/ui/properties/ModelNodeEditor.js, src/ui/properties/SpawnerNodeEditor.js, src/ui/properties/VideoNodeEditor.js
closes #414 This PR adds support to show/edit attribution information in scene assets, specifically Model, Video, Image and Spawners. What this does right now:
- Update nodes attributions when media is resolved so in all cases where new media is added or updated (asset dropoff, node url update or from media gallery)
- All assets attribution is initially set based in the meta information returned by `resolveMedia` and then updated with the asset file info in case it's available (i.e. GLTF embedded asset info)
- Displays the attribution information in the Publishing dialog, one line per attribution element
It also fixes an issue with adding new source to audio/video nodes that threw an exception in Chrome an the updated element didn't work:
```
Cause:
Failed to execute …
```
=> Add support for manual attribution update

src/api/Api.js, src/editor/nodes/SceneNode.js
Filter out empty attribution strings when publishing
=> Check for empty attribution strings

src/ui/properties/SpotLightNodeEditor.js
Changed Spot Light Intensity Unit from 'Degrees' to 'Candela'  [here.](https://github.com/mozilla/Spoke/blob/master/src/ui/properties/SpotLightNodeEditor.js#L61)
It fixes [#986](https://github.com/mozilla/Spoke/issues/986)
=> Updated unit of Spot Light Intensity

src/editor/gltf/GLTFExporter.js
This was fixed upstream in this PR and we hadn't pulled in the change yet. Probably another reason to move back to the official GLTFExporter now that a plugin system exists. https://github.com/mrdoob/three.js/pull/17433
=> Fix alpha mask when alpha cutoff set to 0.5

Jenkinsfile, scripts/hab-build-and-push.sh
Changes the jenkins script to allow for building QA packages and adds a prompt for the QA promotion slack command.
=> Jenkins changes for QA builds

src/api/Api.js, src/ui/App.js, src/ui/inputs/FileInput.js, src/ui/projects/CreateProjectPage.js, src/ui/projects/CreateScenePage.js, src/ui/projects/ProjectGrid.js, src/ui/projects/ProjectGridItem.js, src/ui/projects/ProjectsPage.js
Added support for publishing scenes directly from a GLB file. They are surfaced along side other projects on the projects page, but don't actually have a project associated with them. These GLB files are expected to be complete scenes including navmeshes, spawn points, collisions, etc, likely created using the Hubs Blender Exporter.
Its intentionally not surfaced as a primary call to action, and the intended users for this will likely already know they want it, and what its for.  Its likely we will eventually want to move this elsewhere and/or integrate it into our other tooling more directly, but we decided to surface it in Spoke as a starting point.
Todo:
=> Add support for creating scenes directly from GLBs

src/editor/nodes/AmbientLightNode.js, src/editor/nodes/AudioNode.js, src/editor/nodes/BoxColliderNode.js, src/editor/nodes/DirectionalLightNode.js, src/editor/nodes/EditorNodeMixin.js, src/editor/nodes/FloorPlanNode.js, src/editor/nodes/GroundPlaneNode.js, src/editor/nodes/GroupNode.js, src/editor/nodes/HemisphereLightNode.js, src/editor/nodes/ImageNode.js, src/editor/nodes/KitPieceNode.js, src/editor/nodes/LinkNode.js, src/editor/nodes/MediaFrameNode.js, src/editor/nodes/ModelNode.js, src/editor/nodes/ParticleEmitterNode.js, src/editor/nodes/PointLightNode.js, src/editor/nodes/ScenePreviewCameraNode.js, src/editor/nodes/SimpleWaterNode.js, src/editor/nodes/SkyboxNode.js, src/editor/nodes/SpawnPointNode.js, src/editor/nodes/SpawnerNode.js, src/editor/nodes/SpotLightNode.js, src/editor/nodes/TriggerVolumeNode.js, src/editor/nodes/VideoNode.js, src/editor/nodes/WayPointNode.js
I originally thought we'd completely move over to an ECS data structure in Spoke, but that hasn't been the case. The serialization format uses it, but Nodes are still OOP. This changes the property `legacyComponentName` to `componentName` to indicate the fact that this is in-fact the current way of doing things.
=> legacyComponentName -> componentName

src/ui/properties/GroupNodeEditor.js
This PR moves the GroupNodeEditor to a functional component. In the new contributor guide I'd like to use the Group Node as an example and have it using the most recent best practices.
=> Refactor GroupNodeEditor

src/ui/EditorContainer.js
I'd like to remove the wiki since it's not up to date anymore. We'll use the docs site instead.
=> Make Spoke controls link to the Hubs docs instead of Spoke wiki

src/editor/Editor.js, src/editor/gltf/GLTFExporter.js, src/editor/gltf/GLTFLoader.js, src/editor/gltf/moz-hubs-components.js
This adds support for importing GLTFs that contain Hubs components with node references. The GLTF index in values of specific components (defined in `HUBS_NODEREF_COMPONENTS` for now) is remapped to a UUID of the target node at import time. At export time this value is remapped back to the index of the same node in the final exported GLTF. This piggybacks on the existing method used in Spoke for exporting these references.  We should be able to apply a similar technique for other sorts of internal references (materials, images, etc) as needed. We plan to replace the GLTFLoader/GLTFExporter soon but this should be easily ported to the new plugin API.
Separately, also allows the GLTF exporter to export cameras so they are correctly passed through.
These are both used in the new …
=> Allow passing through components with node refferences

src/editor/gltf/moz-hubs-components.js
This allows `audio-target`s to correctly pass through Spoke
=> Add audio-target.srcNode to nodeRef components

src/ui/properties/AudioNodeEditor.js, src/ui/properties/VideoNodeEditor.js
During the Audio zones PR some media properties were accidentally removed from the audio and video nodes.
This PR restores those params
Fixes https://github.com/mozilla/Spoke/issues/1160
=> Restore lost media params

src/editor/nodes/AudioNode.js, src/editor/nodes/VideoNode.js
Disable artificial distance based attenuation for stereo audio/video elements.
Related https://github.com/mozilla/hubs/pull/4608
=> Disable artificial attenuation for stereo audio/video

docs/creating-custom-elements.md
- Line 38: `SpinningCubeEditor` -> `SpinningCubeNodeEditor`
- When I following the example in 'docs/creating-custom-elements` I meet the error
- Example wrote the `SpinningCubeEditor`. but, should write `SpinningCubeNodeEditor`
=> Fix `creating-custom-elements` example

webpack.config.js
Why
---
An “Invalid Host header” error message appears in the browser when Hubs is orchestrated with Docker Compose
What
----
* Set sufficient self-signed certificate key size for dev
* Allow internal hostname to be supplied by OS var
=> Prepare for local orchestration

.github/workflows/spoke-RetPageOrigin.yml
Use the Hubs Foundation's docker hub repository for building and pushing docker images.
=> Hubs Foundation docker registry update

src/ui/EditorContainer.js
The Submit Feedback buttons in the Spoke project editor main menu (and its Help submenu) currently link to a Google form for sending feedback to Mozilla.  This commit replaces the Mozilla form links with a Discord invite link so feedback about Spoke will come to the Hubs Discord server instead.
=> [Mozilla Branding Removal] Replace Mozilla Spoke feedback form link with a Discord invite
