- src/client/ui/inputs/ColorInput.js
- src/client/ui/inputs/ColorInput.scss
- Changes:
- Added a color block and an input as the default color input.
- Enabled color picker after clicking on the color block.
- Remove alpha channel in the color picker.
> Improve color picker

- package-lock.json
- package.json
- src/client/editor/SceneLoader.js
- src/client/ui/panels/HierarchyPanelContainer.js
- Changes:
- Displayed the warning message with `SnackBar` at the bottom of `HierarchyPanel`.
- Render duplicate nodes with the warning style.
- Automatically generate node names with the node path if there's a duplicate.
- Added the tooltip on nodes with duplicate names to show the original name.
> Warning display - duplicate node names in the inherited file.

- src/client/editor/Editor.js
> Fix duplicate names

- src/client/ui/panels/HierarchyPanelContainer.js
- changes:
- saved collapsed into `userData` as `_collapsed`.
- updated `userData._collapsed` while the change of the tree is triggered by collapse events.
- created the tree based on the status of `userData._collapsed`.
> Update collapse status

- package-lock.json
- package.json
- src/client/ui/inputs/CompoundNumericInput.js
- src/client/ui/inputs/CompoundNumericInput.scss
- src/client/ui/inputs/componentTypeMappings.js
- src/client/ui/panels/PropertiesPanelContainer.js
> Add slidebar

- package-lock.json
- package.json
- src/client/editor/Project.js
- src/client/ui/EditorContainer.js
- src/client/ui/FileDropTarget.js
- src/client/ui/NativeFileDropTarget.js
- src/client/ui/panels/AssetExplorerPanelContainer.js
- src/server/index.js
> Add support for external gltf/glb dnd

- src/client/ui/inputs/NumericInput.js
> Fix input reset while clicking off the slider.

- package-lock.json
- package.json
- src/client/editor/Editor.js
- src/client/ui/EditorContainer.js
- src/client/ui/dialogs/FileDialog.js
- src/client/ui/inputs/FileInput.js
- src/client/ui/inputs/StringInput.js
- src/client/ui/panels/PropertiesPanelContainer.js
- src/client/utils/url-path.js
- test/client/utils/index.test.js
- test/helpers/browser-env-entry.js
> FileDialog UX

- src/client/editor/Viewport.js
- src/client/ui/EditorContainer.js
- src/client/ui/menus/SnappingDropdown.js
- src/client/ui/menus/ToolBar.js
- src/client/ui/menus/ToolToggle.js
- src/client/ui/panels/ViewportPanelContainer.js
- Improvements for:
- Toolbar basics: #22 
- Basic snapping options: #23 
- Default degree value for snapping option: #161
- Toolbar dropdown fixed position: #171 
- Remove select button: #172  
- Hotkeys binding: #173
> Toolbar Improvement

- src/client/ui/AddComponentDropdown.js
- src/client/ui/panels/PropertiesPanelContainer.js
> Prevent sending change event while the input value is empty.

- src/client/editor/Editor.js
- src/client/editor/Project.js
- src/client/editor/components/GLTFModelComponent.js
- src/client/ui/EditorContainer.js
- src/client/ui/dialogs/PublishDialog.js
- src/client/ui/dialogs/dialog.scss
- src/client/ui/panels/PropertiesPanelContainer.js
- src/server/index.js
> Aggregate, store and publish attribution from imported models

- src/client/editor/Editor.js
- src/client/editor/components/GroundPlaneComponent.js
- src/client/editor/components/index.js
- src/client/ui/AddNodeActionButtons.js
> Add ground plane component that gets included in nav mesh

- src/client/editor/Editor.js
- src/client/editor/Viewport.js
- src/client/ui/RendererStats.js
- src/client/ui/RendererStats.scss
- src/client/ui/panels/ViewportPanelContainer.js
Seems nice to have. Looks like this:
> Add viewport status bar with rendering stats

- src/client/ui/EditorContainer.js
- src/client/ui/panels/PropertiesPanelContainer.js
> Disable static mode in basic UI

- src/client/editor/Editor.js
> Fix duplicating animations.

- src/client/ui/dialogs/AddModelDialog.js
- src/client/ui/inputs/Vector3Input.js
Removes a console log and warning about duplicate component keys.
> Clean up some console logs/warnings

- src/client/ui/inputs/BooleanInput.js
- src/client/ui/inputs/BooleanInput.scss
Fixes #301
They look like this now:
> Fix boolean input styling.

- src/client/editor/Editor.js
- src/client/ui/EditorContainer.js
- src/client/ui/dialogs/PublishDialog.js
- src/client/ui/dialogs/dialog.scss
- src/server/index.js
> Add user attribution field to publish dialog. Remove description field

- .eslintrc.js
- src/client/editor/Editor.js
- src/client/editor/MeshCombinationGroup.js
- src/client/editor/utils/asyncTraverse.js
- src/client/editor/utils/getImageData.js
- src/client/editor/utils/hashImage.js
- src/client/editor/utils/keysEqual.js
Reduces the total number of meshes, materials, and textures in final exported model.
> Combine meshes with identical materials on export

- src/client/editor/commands/MoveObjectCommand.js
> Undoing MoveObjectCommand reapplies original transform.

- src/client/api/Project.js
- src/client/editor/Editor.js
Waiting on this to be updated in Reticulum before merging.
> Update max upload size to 128MB

- src/client/ui/App.js
Adds the option to export as a binary glTF file.
Closes #365
> Support exporting glb files.

- src/client/editor/Editor.js
> Populate duplicate name counters when loading scene.

- src/client/editor/Viewport.js
> Center viewport when loading new scene

- src/client/ui/styles/global.scss
> New scrollbar styling

- src/client/editor/Editor.js
- src/client/editor/Viewport.js
- src/client/editor/commands/AddObjectCommand.js
- src/client/editor/commands/RemoveObjectCommand.js
- src/client/editor/nodes/DirectionalLightNode.js
- src/client/editor/nodes/EditorNodeMixin.js
- src/client/editor/nodes/ModelNode.js
- src/client/editor/nodes/PointLightNode.js
- src/client/editor/nodes/SceneNode.js
- src/client/editor/nodes/SkyboxNode.js
- src/client/editor/nodes/SpotLightNode.js
- src/client/ui/properties/SkyboxNodeEditor.js
- src/client/ui/viewport/ViewportPanelContainer.js
> Use the skybox as the environment map

- src/client/editor/nodes/ModelNode.js
> Fix exporting animations

- src/client/editor/nodes/PointLightNode.js
- src/client/editor/nodes/SpotLightNode.js
> Fix light helper visibility

- package-lock.json
- package.json
- src/client/editor/Editor.js
- src/client/editor/nodes/EditorNodeMixin.js
- src/client/editor/nodes/TriggerVolumeNode.js
- src/client/editor/utils/cloneObject3D.js
- src/client/editor/utils/isEmptyObject.js
- src/client/index.js
- src/client/ui/App.js
- src/client/ui/contexts/SettingsContext.js
- src/client/ui/inputs/BooleanInput.js
- src/client/ui/inputs/BooleanInput.scss
- src/client/ui/inputs/ColorInput.js
- src/client/ui/inputs/CompoundNumericInput.js
- src/client/ui/inputs/EulerInput.js
- src/client/ui/inputs/NumericInput.js
- src/client/ui/inputs/SelectInput.js
- src/client/ui/inputs/StringInput.js
- src/client/ui/inputs/Vector3Input.js
- src/client/ui/properties/TriggerVolumeNodeEditor.js
- src/client/ui/styles/common.scss
- src/client/ui/viewport/AddNodeActionButtons.js
https://github.com/mozilla/hubs/pull/888
> Add trigger-volume node and experimental features setting.

- src/client/editor/MeshCombinationGroup.js
- src/client/editor/nodes/EditorNodeMixin.js
Exported models take visibility into account when combining meshes.
> Fix invisible mesh combination.

- src/ui/library/LibrarySearchContainer.js
> Fix search abort

- webpack.config.js
> Fix source maps

- src/ui/properties/LinkNodeEditor.js
> Add url field to link node editor

- src/editor/controls/SpokeTransformControls.js
> Fix transform controls sort order

- src/ui/properties/VideoNodeEditor.js
> Fix typo in VideoNode description

- src/editor/MeshCombinationGroup.js
> Fix texture hash cache

- src/editor/Editor.js
- src/editor/MeshCombinationGroup.js
- src/editor/nodes/EditorNodeMixin.js
- src/editor/nodes/GroundPlaneNode.js
- src/ui/EditorContainer.js
> MOZ_hubs_components

- src/ui/EditorContainer.js
> Import legacy .spoke scenes

- scripts/run-local-reticulum.sh
- src/api/Api.js
- src/ui/dialogs/LibraryDialog.js
- src/ui/inputs/Button.scss
- src/ui/inputs/LibraryInput.js
- src/ui/inputs/MenuButton.js
- src/ui/library/AssetContextMenu.js
- src/ui/library/AssetsLibrary.js
- src/ui/library/ImagesLibrary.js
- src/ui/library/LibraryContainer.js
- src/ui/library/LibraryGridItem.js
- src/ui/library/LibrarySearchContainer.js
- src/ui/library/ModelsLibrary.js
- src/ui/library/ProjectAssetContextMenu.js
- src/ui/library/VideosLibrary.js
- src/ui/projects/ProjectGrid.js
- src/ui/projects/ProjectGridItem.js
- src/ui/projects/ProjectGridItem.scss
- src/ui/projects/ProjectsPage.js
- src/ui/projects/ProjectsPage.scss
- Added ability to delete a project
- Added ability to delete an asset
- Assets uploaded in the assets tab are no longer automatically added to your project and are added when you first use them.
- Added ability to remove an asset from your project
- Added ability to cancel uploads
- Upload progress now displays information about what file you are on when uploading multiple files
> Project / Assets / ProjectAssets deletion

- src/editor/nodes/ModelNode.js
- src/ui/inputs/LibraryInput.js
- src/ui/library/ModelsLibrary.js
- src/ui/properties/ModelNodeEditor.js
- src/ui/properties/SpawnerNodeEditor.js
> Scale correction

- src/editor/controls/InputManager.js
Reduces memory allocations and stops react from handling canvas mouse move events
> Input Manager Performance

- src/api/Api.js
Use farspark for media thumbnail images
> Farspark media thumbnails

- src/editor/Editor.js
- src/editor/controls/SpokeControls.js
- src/editor/utils/getIntersectingNode.js
- src/ui/library/LibraryContainer.js
> Spawn objects in front of camera using raycaster

- src/ui/inputs/LibraryInput.js
- src/ui/inputs/ModelInput.js
> Fix updating media via library input

- src/editor/objects/Video.js
> Fix cloning videos

- src/editor/nodes/ModelNode.js
> Fix publishing with empty models

- src/api/PublishDialog.js
- src/ui/dialogs/Dialog.js
> Fix validation in dialogs

- src/editor/objects/PhysicalSpotLight.js
- src/ui/properties/SpotLightNodeEditor.js
> Set non-zero minimum for outer cone angle

- src/ui/library/VideosLibrary.js
> Remove youtube

- src/api/Api.js
- src/api/AuthContainer.js
- src/api/AuthEmailSentMessage.js
- src/api/LoginDialog.js
- src/ui/dialogs/Dialog.js
> Cancel Auth

- src/editor/nodes/EditorNodeMixin.js
- src/editor/nodes/ImageNode.js
- src/editor/nodes/ModelNode.js
- src/editor/nodes/VideoNode.js
- src/editor/objects/Model.js
- src/ui/library/ElementsLibrary.js
> Fix media errors and add default urls

- src/editor/Editor.js
> Fix filename case sensitivity

- src/editor/nodes/SpawnerNode.js
> Fix spawner scale

- src/ui/onboarding/Onboarding.js
> Remove snapping image fron save step

- src/ui/library/LibrarySearchContainer.js
- src/ui/library/VideosLibrary.js
> Fix tenor only searching trending

- src/api/Api.js
> Fix isAuthenticated method when token is null

- src/ui/hierarchy/HierarchyPanelContainer.js
- src/ui/onboarding/Onboarding.js
- src/ui/utils.js
Fixes #500 
Fixes #116 
Fixes #375 
Fixes #527
> Fix hierarchy handlers

- src/editor/objects/Image.js
> Fix image scaling on load

- src/ui/EditorContainer.js
- src/ui/onboarding/Onboarding.js
- src/ui/onboarding/OnboardingContainer.js
> Allow replaying of tutorial on finish/skip

- src/api/Api.js
> Show final onboarding modal after confirming publish

- src/editor/MeshCombinationGroup.js
- src/editor/utils/materials.js
> Dedupe textures on export

- src/editor/History.js
- src/editor/commands/SetObjectPropertyCommand.js
- src/ui/inputs/EulerInput.js
- src/ui/inputs/NumericInput.js
- src/ui/inputs/NumericInput.scss
- src/ui/inputs/NumericInputGroup.js
- src/ui/inputs/RadianNumericInputGroup.js
- src/ui/inputs/Scrubber.js
- src/ui/inputs/Scrubber.scss
- src/ui/inputs/Vector3Input.js
- src/ui/properties/AmbientLightNodeEditor.js
- src/ui/properties/DirectionalLightNodeEditor.js
- src/ui/properties/FloorPlanNodeEditor.js
- src/ui/properties/HemisphereLightNodeEditor.js
- src/ui/properties/LightShadowProperties.js
- src/ui/properties/PointLightNodeEditor.js
- src/ui/properties/SkyboxNodeEditor.js
- src/ui/properties/SpotLightNodeEditor.js
- src/ui/properties/TransformPropertyGroup.js
- src/ui/properties/VideoNodeEditor.js
- src/ui/toolbar/SnappingDropdown.js
- src/ui/utils.js
Fixes #417
Fixes #67
Fixes #499
Fixes #544
> Refactor numeric input

- Jenkinsfile
- README.md
- SUPPORT.md
- package.json
- src/api/PublishDialog.js
- src/ui/EditorContainer.js
- src/ui/dialogs/Dialog.scss
- src/ui/dialogs/PreviewDialog.scss
- src/ui/dialogs/SupportDialog.js
- src/ui/navigation/Footer.js
- src/ui/navigation/NavBar.js
> Update links and add support dialog

- package-lock.json
- package.json
- src/editor/controls/FlyControls.js
- src/editor/controls/InputManager.js
- src/editor/controls/SpokeControls.js
- src/editor/controls/TransformControls.js
- src/editor/controls/input-mappings.js
Fixes #613
Fixes #617 
Fixes #552 
Fixes #519
> Switch orbit to lmb and add hotkeys support

- package-lock.json
- package.json
- src/editor/Editor.js
- src/editor/History.js
- src/editor/commands/SetObjectPropertyCommand.js
- src/editor/commands/SetPositionCommand.js
- src/editor/commands/SetRotationCommand.js
- src/editor/commands/SetScaleCommand.js
- src/editor/controls/FlyControls.js
- src/editor/controls/InputManager.js
- src/editor/controls/SpokeControls.js
- src/editor/controls/TransformControls.js
- src/editor/controls/input-mappings.js
- src/ui/inputs/EulerInput.js
- src/ui/inputs/Scrubber.js
- src/ui/inputs/Vector3Input.js
- src/ui/properties/PropertiesPanelContainer.js
- src/ui/properties/TransformPropertyGroup.js
> Improve properties panel rendering performance when scrubbing / transforming

- src/ui/inputs/SelectInput.js
- src/ui/library/ImagesLibrary.js
- src/ui/library/LibrarySearchContainer.js
- src/ui/library/VideosLibrary.js
Fixes #621 
Fixes #620
Fixes #467
> Fix search parameters

- src/api/AuthEmailSentMessage.js
- src/editor/controls/SpokeControls.js
- src/ui/dialogs/LoginDialogLink.js
- src/ui/onboarding/OnboardingDialog.js
- src/ui/onboarding/OnboardingPopover.js
- src/ui/viewport/ViewportPanelContainer.js
- src/ui/viewport/ViewportPanelContainer.scss
> Add controls info to viewport

- src/ui/EditorContainer.js
- src/ui/toolbar/ToolBar.js
- src/ui/toolbar/ToolBar.scss
- src/ui/toolbar/ToolButton.js
- src/ui/toolbar/ToolToggle.js
> Add keyboard shortcuts to toolbar and main menu

- src/editor/controls/SpokeControls.js
- src/editor/controls/input-mappings.js
> Add deselect hotkey

- src/editor/Editor.js
https://github.com/KhronosGroup/glTF-Generator-Registry/pull/2
Fixes #489
> Add glTF asset generator string

- src/editor/nodes/ImageNode.js
- src/editor/nodes/ModelNode.js
- src/editor/nodes/SpawnerNode.js
- src/editor/nodes/VideoNode.js
> Only reload media when the src changes

- package-lock.json
- package.json
- src/index.js
Adds support for Chrome < 66, Firefox < 57, and Edge < 16
> Add AbortController polyfill

- src/editor/nodes/SpotLightNode.js
> Make spotlight ignore selection raycast

- src/editor/nodes/SkyboxNode.js
- src/ui/inputs/CompoundNumericInput.js
- src/ui/inputs/EulerInput.js
- src/ui/inputs/NumericInput.js
- src/ui/inputs/RadianNumericInputGroup.js
- src/ui/inputs/Scrubber.js
- src/ui/inputs/Vector3Input.js
- src/ui/properties/AmbientLightNodeEditor.js
- src/ui/properties/DirectionalLightNodeEditor.js
- src/ui/properties/FloorPlanNodeEditor.js
- src/ui/properties/HemisphereLightNodeEditor.js
- src/ui/properties/PointLightNodeEditor.js
- src/ui/properties/SkyboxNodeEditor.js
- src/ui/properties/SpotLightNodeEditor.js
- src/ui/properties/TransformPropertyGroup.js
- src/ui/properties/VideoNodeEditor.js
- src/ui/toolbar/SnappingDropdown.js
> Fix up numeric input parameters

- src/editor/nodes/SceneNode.js
- src/ui/EditorContainer.js
Fixes https://github.com/mozilla/Spoke/issues/717
> Properly clone metadata when serializing scene

- src/editor/commands/MoveObjectCommand.js
> Fix reparenting nodes

- src/editor/controls/FlyControls.js
- src/editor/controls/input-mappings.js
> Use Q/E to raise/lower in fly mode

- src/editor/Viewport.js
> Fix selection after resizing panel

- src/editor/objects/Video.js
> Fix cloning video node

- src/ui/projects/ProjectsPage.js
Just moving projects section above Templates :)
Fixes https://github.com/mozilla/Spoke/issues/715
> Moving Projects section above templates

- src/editor/objects/PhysicalSpotLight.js
> Add floor to spotlight penumbra

- .eslintrc.js
- package.json
- src/api/Api.js
- src/api/SketchfabZipLoader.js
- src/ui/dialogs/SaveNewProjectDialog.js
- src/ui/hierarchy/HierarchyPanelContainer.js
- src/ui/layout/Popover.js
- src/ui/layout/Positioner.js
- src/ui/library/LibrarySearchContainer.js
- yarn.lock
- Add eslint-plugin-react-hooks
- Add linting to pretest CI step
- Fix linting errors
> eslint react hooks

- src/editor/Editor.js
- src/editor/History.js
- src/editor/commands/DuplicateMultipleCommand.js
- src/editor/controls/SpokeControls.js
- src/editor/nodes/KitPieceNode.js
- src/editor/nodes/ModelNode.js
- src/editor/nodes/SpawnerNode.js
- test/unit/Editor.test.js
There were a number of bugs related to side effects when selecting objects when in placement / grab mode. Those should all be fixed now.
> Fix Placement / Batching Bugs

- src/ui/EditorContainer.js
Fixes https://github.com/mozilla/Spoke/issues/795
> Fix name assignment

- src/ui/EditorContainer.js
> Navigate to templates page on new project

- src/ui/layout/MediaGrid.js
> Mute videos in assets panel

- src/api/Api.js
- src/ui/EditorContainer.js
- src/ui/GlobalStyle.js
- src/ui/assets/AssetGrid.js
- src/ui/assets/AssetTooltip.js
- src/ui/assets/ImageMediaSource.js
- src/ui/assets/ModelMediaSource.js
- src/ui/assets/VideoMediaSource.js
- src/ui/contexts/OnboardingContext.js
- src/ui/layout/MediaGrid.js
> Add titles and better tooltips to asset grid

- src/ui/EditorContainer.js
- src/ui/assets/MediaSourcePanel.js
This fixes issue #812. Added Save As Future.
> Added option for save as in editorContainer screen

- src/editor/nodes/WayPointNode.js
- src/ui/properties/WayPointNodeEditor.js
Adds an option for waypoints to disable teleporting. Accompanies https://github.com/mozilla/hubs/pull/1958
> Add willDisableTeleporting as waypoint option

- src/ui/assets/KitSource.js
Use cors-proxy for all kit assets
> CORS Proxy kit assets

- package.json
- src/ui/GlobalStyle.js
- src/ui/assets/AssetGrid.js
- src/ui/inputs/InputGroup.js
- src/ui/inputs/NumericInputGroup.js
- src/ui/inputs/NumericStepperInput.js
- src/ui/layout/Tooltip.js
- src/ui/properties/AudioSourceProperties.js
- src/ui/properties/PropertiesPanelContainer.js
- src/ui/toolbar/ToolBar.js
- src/ui/toolbar/ToolButton.js
- yarn.lock
React tooltip had some issues with positioning and getting stuck open. I've replaced it with my own implementation which fixes these issues.
This PR also adds tooltips to a number of audio properties.
> Remove react-tooltip and add tooltips for audio properties

- src/editor/Editor.js
- src/editor/nodes/ModelNode.js
- src/editor/objects/Model.js
- src/ui/toolbar/ToolBar.js
You can now preview model animations, videos, and audio in Spoke! To enable this experimental feature go to File -> Developer -> Enable Experimental Features. You'll then see a play button in the toolbar that you can use to play/pause the preview.
> Experimental Preview Mode

- src/api/Api.js
- src/ui/EditorContainer.js
Fixes #854 
Fixes #560 
Fixes #754
> Fix save and publish bugs

- src/editor/Editor.js
> Fix pasting links

- src/editor/controls/SpokeControls.js
> Don't raycast on invisible objects

- src/editor/nodes/FloorPlanNode.js
> Fix heightfield visibility when not selected

- src/editor/controls/SpokeControls.js
- src/editor/objects/TransformGizmo.js
> Highlight hovered transform axis

- src/editor/Editor.js
> Preserve object parent when duplicating objects

- src/editor/gltf/GLTFLoader.js
The GLTFExporter doesn't support exporting interleaved accessors. Rather than implementing that feature along with proper cloning of interleaved accessors,  this PR converts all interleaved accessors to non-interleaved accessors at load time. This comes at a small performance cost, but makes the implementation significantly simpler. We may choose to fully support interleaved accessors in the future.
> Convert interleaved accessors to non-interleaved

- src/api/Api.js
Cache media resolver responses to improve project load times with duplicate requests, etc.
> Cache media resolver responses

- src/ui/EditorContainer.js
Ensures that a scene is saved after importing and publishing without any other modifications.
> Mark scene modified after importing project

- src/editor/gltf/extensions/exporter/LightmapExporterExtension.js
Fixes #1023 Make sure the extensions object is present before adding the extension
> Make sure the extensions object is present before adding the extension

- src/editor/nodes/MediaFrameNode.js
> Don't show media frame helper in scene preview

- src/editor/nodes/KitPieceNode.js
- src/editor/nodes/ModelNode.js
- src/editor/objects/Model.js
Ensures `activeClipIndices` is an array :
https://discordapp.com/channels/498741086295031808/684465503040831520/762762251949309963
> Fix bug preventing certain scenes from being published

- src/config.js
Missed to push the config.js file
> Add missing config for audio zones

- src/config.js
- src/editor/nodes/MirrorNode.js
- src/editor/objects/Mirror.js
- src/ui/properties/MirrorNodeEditor.js
- Add Mirro component
- https://github.com/mozilla/hubs/pull/5225
~~Copy and paste mirror, the pasted mirror's color is not changed.~~
~~But when publish scene, in hubs color is correct.~~
~~I don't know how to fix it. plz help.~~
I fix it. clear.
This feature is only apply plane mirror.
But, I'll add shape and texture properties in future.
> Add Mirror component
